# -*- coding: utf-8 -*-
"""Analisis-digital-en-TechCorp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1at5ThAzVa2BIiFhvJpA8V0IkKTiAZA78
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# 1. Preparación del entorno
if not os.path.exists('reports'):
    os.makedirs('reports')

# Cargar y limpiar
df = pd.read_csv('05. transformacion_digital_dataset.csv')
df['fecha'] = pd.to_datetime(df['fecha'])

# 2. Gráfico de ROI y Madurez (Impacto Financiero)
plt.figure(figsize=(10, 5))
plt.plot(df['fecha'], df['roi_transformacion_porcentaje'], marker='o', label='ROI %', color='#1f77b4')
plt.plot(df['fecha'], df['madurez_digital_score'] * 5, marker='s', label='Madurez Digital (Escalada)', color='#2ca02c')
plt.title('Evolución del ROI vs Madurez Digital', fontsize=14)
plt.legend()
plt.grid(alpha=0.3)
plt.savefig('reports/01_roi_vs_madurez.png')

# 3. Gráfico de Capacitación vs Calidad
plt.figure(figsize=(10, 5))
sns.scatterplot(data=df, x='empleados_capacitados_porcentaje', y='tasa_defectos_porcentaje',
                size='productividad_manufactura', hue='productividad_manufactura', palette='viridis')
plt.title('Impacto de la Capacitación en la Calidad', fontsize=14)
plt.savefig('reports/02_capacitacion_impacto.png')

# 4. Análisis Cultural (Resistencia vs Innovación)
plt.figure(figsize=(10, 5))
plt.fill_between(df['fecha'], df['resistencia_cambio_score'], color="red", alpha=0.2, label='Resistencia')
plt.plot(df['fecha'], df['innovacion_index'] / 10, color="blue", label='Innovación (Escalada)')
plt.title('Cultura: Resistencia vs Innovación', fontsize=14)
plt.legend()
plt.savefig('reports/03_cultura.png')
